### ISSUE TITLE
[Consensus] Formalize Attacks

### ISSUE THREAD

**Issue by sternhenri** [filecoin-project/consensus#26]
- This epic will hopefully help resolve a lot of the underlying GH issues related to specific attacks
- Through this epic, we work through a more formal model for understanding EC, which will be usable elsewhere

**Short Term**
- [x] Pin down dependencies section setting up attack work (ie write down agreed upon EC construction to evaluate)
- [ ] Do initial analysis of each attack:
  - [ ] Challenge Grinding or multi-chain forking
  - [ ] Nothing at Stake
  - [ ] Selfish Mining
  - [ ] Posterior Corruption

**Medium Term**
- [ ]  Present the above for FIL research week to iterate in person
- [ ] Select and bring in relevant outside researchers to critique/pursue work
